name: flora_emosens
description: A smart plant monitoring and care application
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  http: ^1.1.0
  camera: ^0.10.5+5
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^16.2.0
  google_fonts: ^5.1.0
  sensors_plus: ^4.0.2
  flutter_animate: ^4.3.0
  flutter_launcher_icons: ^0.13.1 # For launcher icons
  get: ^4.6.5 # For better state management and navigation
  intl: ^0.18.0 # For internationalization and date formatting
  animations: ^2.0.6 # For material motion animations

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
